epuck2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

